let tables = {
    chauffeur: ["CREATE TABLE chauffeur (chauf_id integer NOT NULL, chauf_nom character varying(100), chauf_tel character varying(50))", 
                "CREATE SEQUENCE chauffeur_chauf_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    chauffvehic: ["CREATE TABLE chauffvehic (chaufvehic_id integer NOT NULL, vehic_numero character varying(8) NOT NULL, chauf_id integer NOT NULL, chaufvehic_date date)", 
                "CREATE SEQUENCE chauffvehic_chaufvehic_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    cooperative: ["CREATE TABLE cooperative (coop_id integer NOT NULL, coop_nom character varying(50), coop_adresse character varying(100), coop_etat_parametre boolean)", 
                "CREATE SEQUENCE cooperative_coop_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    etat_reservation: ["CREATE TABLE etat_reservation (etat_res_id integer NOT NULL, etat_res_libelle character varying(50) )", 
                "CREATE SEQUENCE etat_reservation_etat_res_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    frais: ["CREATE TABLE frais (frais_id integer NOT NULL, itin_id integer, typv_id integer, frais_montant double precision)", 
                "CREATE SEQUENCE frais_frais_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    guichet: ["CREATE TABLE guichet (guichet_id integer NOT NULL,ville_id integer NOT NULL,guichet_nom character varying(50),guichet_adresse character varying(255) )", 
                "CREATE SEQUENCE guichet_guichet_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    guichetier: ["CREATE TABLE guichetier (guichetier_id integer NOT NULL, guichet_id integer NOT NULL, guichetier_nom character varying(100), guichetier_telephone character(50), guichetier_adresse character varying(255))", 
                "CREATE SEQUENCE guichetier_guichetier_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    itineraire: ["CREATE TABLE itineraire (itin_id integer NOT NULL, guichet_id integer NOT NULL, itin_depart integer NOT NULL, itin_arrivee integer NOT NULL)", 
                "CREATE SEQUENCE itineraire_itin_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    listage: ["CREATE TABLE listage ( listage_id integer NOT NULL, vehic_numero character varying(8) NOT NULL, listage_etat character varying(10), listage_ordre integer)", 
                "CREATE SEQUENCE listage_listage_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    mode_payement: ["CREATE TABLE mode_payement ( modep_id integer NOT NULL, modep_libelle character varying(50), modep_numero character varying(100))", 
                "CREATE SEQUENCE mode_payement_modep_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    parametre: ["CREATE TABLE parametre ( param_id integer NOT NULL, guichet_id integer, param_heuredepfixe integer, param_vehicdiffheuredep integer, param_vehicchaqueclasse integer, param_chaufpermute integer, param_autorisationsansavance integer, param_invaliderresretardpaye integer, param_invaliderresnonpaye integer, param_paritinparclasse integer, param_nbvehicreservsimultane integer, param_annulerreservparclient integer, param_affectchauffvehic integer)", 
                "CREATE SEQUENCE parametre_param_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    passager: ["CREATE TABLE passager ( passager_id integer NOT NULL, passeger_tel character varying(50), passager_nom character varying(100), passager_terminal character varying(100))", 
                "CREATE SEQUENCE passager_passager_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    reservation: ["CREATE TABLE reservation ( reserv_id integer NOT NULL, modep_id integer NOT NULL, frais_id integer NOT NULL, etat_res_id integer NOT NULL, voy_id integer NOT NULL, passager_id integer NOT NULL, reserv_nb_passager integer, reserv_place character varying(150), reserv_avance double precision, reserv_montant_total double precision, reserv_date date)", 
                "CREATE SEQUENCE reservation_reserv_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    type_vehicule: ["CREATE TABLE type_vehicule ( typv_id integer NOT NULL, typv_nom character varying(50), typv_description character varying(255), typv_url_image character varying(255))", 
                "CREATE SEQUENCE type_vehicule_typv_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    vehicule: "CREATE TABLE vehicule (vehic_numero character varying(8) NOT NULL, vehic_couleur character varying(10))",	
    province: ["CREATE TABLE province ( prov_id integer NOT NULL, prov_nom character(50), prov_description text)", 
                "CREATE SEQUENCE Province_prov_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],
    ville: ["CREATE TABLE ville (ville_id integer NOT NULL,ville_nom character varying(50),prov_id integer NOT NULL)", 
                "CREATE SEQUENCE ville_ville_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],	
    voyage: ["CREATE TABLE voyage (voy_id integer NOT NULL,listage_id integer NOT NULL,typv_id integer NOT NULL,cat_vehic_id integer NOT NULL,itin_id integer NOT NULL,voy_heure_depart date,voy_heure_arrivee date,voy_etat character varying(20) )", 
                "CREATE SEQUENCE voyage_voy_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1"],
    dafault_values: ["ALTER TABLE ONLY public.chauffeur ALTER COLUMN chauf_id SET DEFAULT nextval('public.chauffeur_chauf_id_seq'::regclass)",
            "ALTER TABLE ONLY public.chauffvehic ALTER COLUMN chaufvehic_id SET DEFAULT nextval('public.chauffvehic_chaufvehic_id_seq'::regclass)",
            "ALTER TABLE ONLY public.cooperative ALTER COLUMN coop_id SET DEFAULT nextval('public.cooperative_coop_id_seq'::regclass)",
            "ALTER TABLE ONLY public.etat_reservation ALTER COLUMN etat_res_id SET DEFAULT nextval('public.etat_reservation_etat_res_id_seq'::regclass)",
            "ALTER TABLE ONLY public.frais ALTER COLUMN frais_id SET DEFAULT nextval('public.frais_frais_id_seq'::regclass)",
            "ALTER TABLE ONLY public.guichet ALTER COLUMN guichet_id SET DEFAULT nextval('public.guichet_guichet_id_seq'::regclass)",
            "ALTER TABLE ONLY public.guichetier ALTER COLUMN guichetier_id SET DEFAULT nextval('public.guichetier_guichetier_id_seq'::regclass)",
            "ALTER TABLE ONLY public.itineraire ALTER COLUMN itin_id SET DEFAULT nextval('public.itineraire_itin_id_seq'::regclass)",
            "ALTER TABLE ONLY public.listage ALTER COLUMN listage_id SET DEFAULT nextval('public.listage_listage_id_seq'::regclass)",
            "ALTER TABLE ONLY public.mode_payement ALTER COLUMN modep_id SET DEFAULT nextval('public.mode_payement_modep_id_seq'::regclass)",
            "ALTER TABLE ONLY public.parametre ALTER COLUMN param_id SET DEFAULT nextval('public.parametre_param_id_seq'::regclass)",
            "ALTER TABLE ONLY public.passager ALTER COLUMN passager_id SET DEFAULT nextval('public.passager_passager_id_seq'::regclass)",
            "ALTER TABLE ONLY public.reservation ALTER COLUMN reserv_id SET DEFAULT nextval('public.reservation_reserv_id_seq'::regclass)",
            "ALTER TABLE ONLY public.type_vehicule ALTER COLUMN typv_id SET DEFAULT nextval('public.type_vehicule_typv_id_seq'::regclass)",
            "ALTER TABLE ONLY public.ville ALTER COLUMN ville_id SET DEFAULT nextval('public.ville_ville_id_seq'::regclass)",
            "ALTER TABLE ONLY public.voyage ALTER COLUMN voy_id SET DEFAULT nextval('public.voyage_voy_id_seq'::regclass)"],
    indexes_and_constraints: ["ALTER TABLE ONLY public.chauffeur ADD CONSTRAINT pk_chauffeur PRIMARY KEY (chauf_id)",
                "ALTER TABLE ONLY public.chauffvehic ADD CONSTRAINT pk_chauffvehic PRIMARY KEY (chaufvehic_id)",
                "ALTER TABLE ONLY public.cooperative ADD CONSTRAINT pk_cooperative PRIMARY KEY (coop_id)",
                "ALTER TABLE ONLY public.etat_reservation ADD CONSTRAINT pk_etat_reservation PRIMARY KEY (etat_res_id)",
                "ALTER TABLE ONLY public.frais ADD CONSTRAINT pk_frais PRIMARY KEY (frais_id)",
                "ALTER TABLE ONLY public.guichet ADD CONSTRAINT pk_guichet PRIMARY KEY (guichet_id)",
                "ALTER TABLE ONLY public.guichetier ADD CONSTRAINT pk_guichetier PRIMARY KEY (guichetier_id)",
                "ALTER TABLE ONLY public.itineraire ADD CONSTRAINT pk_itineraire PRIMARY KEY (itin_id)",
                "ALTER TABLE ONLY public.listage ADD CONSTRAINT pk_listage PRIMARY KEY (listage_id)",
                "ALTER TABLE ONLY public.mode_payement ADD CONSTRAINT pk_mode_payement PRIMARY KEY (modep_id)",
                "ALTER TABLE ONLY public.parametre ADD CONSTRAINT pk_parametre PRIMARY KEY (param_id)",
                "ALTER TABLE ONLY public.passager ADD CONSTRAINT pk_passager PRIMARY KEY (passager_id)",
                "ALTER TABLE ONLY public.reservation ADD CONSTRAINT pk_reservation PRIMARY KEY (reserv_id)",
                "ALTER TABLE ONLY public.type_vehicule ADD CONSTRAINT pk_type_vehicule PRIMARY KEY (typv_id)",
                "ALTER TABLE ONLY public.vehicule ADD CONSTRAINT pk_vehicule PRIMARY KEY (vehic_numero)",
                "ALTER TABLE ONLY public.ville ADD CONSTRAINT pk_ville PRIMARY KEY (ville_id)",
                "ALTER TABLE ONLY public.voyage ADD CONSTRAINT pk_voyage PRIMARY KEY (voy_id)",
                "CREATE INDEX appartenir_fk ON public.voyage USING btree (itin_id)",
                "CREATE INDEX as_13_fk ON public.voyage USING btree (typv_id)",
                "CREATE INDEX as_18_fk ON public.guichetier USING btree (guichet_id)",
                "CREATE INDEX as_19_fk ON public.chauffvehic USING btree (chauf_id)",
                "CREATE INDEX aso_14_fk ON public.frais USING btree (typv_id)",
                "CREATE INDEX aso_15_fk ON public.frais USING btree (itin_id)",
                "CREATE INDEX aso_16_fk ON public.reservation USING btree (frais_id)",
                "CREATE INDEX aso_17_fk ON public.reservation USING btree (modep_id)",
                "CREATE INDEX aso_19_fk ON public.chauffvehic USING btree (vehic_numero)",
                "CREATE INDEX asoc_12_fk ON public.guichet USING btree (ville_id)",
                "CREATE INDEX association_10_fk ON public.reservation USING btree (etat_res_id)",
                "CREATE INDEX association_11_fk ON public.voyage USING btree (cat_vehic_id)",
                "CREATE INDEX association_12_fk ON public.voyage USING btree (listage_id)",
                "CREATE INDEX association_13_fk ON public.listage USING btree (vehic_numero)",
                "CREATE INDEX association_8_fk ON public.reservation USING btree (passager_id)",
                "CREATE INDEX association_9_fk ON public.reservation USING btree (voy_id)",
                "CREATE UNIQUE INDEX chauffeur_pk ON public.chauffeur USING btree (chauf_id)",
                "CREATE UNIQUE INDEX chauffvehic_pk ON public.chauffvehic USING btree (chaufvehic_id)",
                "CREATE UNIQUE INDEX cooperative_pk ON public.cooperative USING btree (coop_id)",
                "CREATE UNIQUE INDEX frais_pk ON public.frais USING btree (frais_id)",
                "CREATE UNIQUE INDEX guichet_pk ON public.guichet USING btree (guichet_id)",
                "CREATE UNIQUE INDEX guichetier_pk ON public.guichetier USING btree (guichetier_id)",
                "CREATE UNIQUE INDEX itineraire_pk ON public.itineraire USING btree (itin_id)",
                "CREATE UNIQUE INDEX listage_pk ON public.listage USING btree (listage_id)",
                "CREATE UNIQUE INDEX mode_payement_pk ON public.mode_payement USING btree (modep_id)",
                "CREATE INDEX par_fk ON public.parametre USING btree (guichet_id)",
                "CREATE UNIQUE INDEX parametre_pk ON public.parametre USING btree (param_id)",
                "CREATE UNIQUE INDEX passager_pk ON public.passager USING btree (passager_id)",
                "CREATE INDEX programer_fk ON public.itineraire USING btree (guichet_id)",
                "CREATE UNIQUE INDEX reservation_pk ON public.reservation USING btree (reserv_id)",
                "CREATE UNIQUE INDEX type_reservation_pk ON public.etat_reservation USING btree (etat_res_id)",
                "CREATE UNIQUE INDEX type_vehicule_pk ON public.type_vehicule USING btree (typv_id)",
                "CREATE UNIQUE INDEX vehicule_pk ON public.vehicule USING btree (vehic_numero)",
                "CREATE UNIQUE INDEX ville_pk ON public.ville USING btree (ville_id)",
                "CREATE UNIQUE INDEX voyage_pk ON public.voyage USING btree (voy_id)",
                "ALTER TABLE ONLY public.chauffvehic ADD CONSTRAINT fk_chauffve_as_19_chauffeu FOREIGN KEY (chauf_id) REFERENCES public.chauffeur(chauf_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.chauffvehic ADD CONSTRAINT fk_chauffve_aso_19_vehicule FOREIGN KEY (vehic_numero) REFERENCES public.vehicule(vehic_numero) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.frais ADD CONSTRAINT fk_frais_aso_14_type_veh FOREIGN KEY (typv_id) REFERENCES public.type_vehicule(typv_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.frais ADD CONSTRAINT fk_frais_aso_15_itinerai FOREIGN KEY (itin_id) REFERENCES public.itineraire(itin_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.guichet ADD CONSTRAINT fk_guichet_asoc_12_ville FOREIGN KEY (ville_id) REFERENCES public.ville(ville_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.guichetier ADD CONSTRAINT fk_guicheti_as_18_guichet FOREIGN KEY (guichet_id) REFERENCES public.guichet(guichet_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.itineraire ADD CONSTRAINT fk_itinerai_programer_guichet FOREIGN KEY (guichet_id) REFERENCES public.guichet(guichet_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.listage ADD CONSTRAINT fk_listage_aso_7_vehicule FOREIGN KEY (vehic_numero) REFERENCES public.vehicule(vehic_numero) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.parametre ADD CONSTRAINT fk_parametr_asos_19_guichet FOREIGN KEY (guichet_id) REFERENCES public.guichet(guichet_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.reservation ADD CONSTRAINT fk_reservat_as_10_etat_res FOREIGN KEY (etat_res_id) REFERENCES public.etat_reservation(etat_res_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.reservation ADD CONSTRAINT fk_reservat_as_8_passager FOREIGN KEY (passager_id) REFERENCES public.passager(passager_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.reservation ADD CONSTRAINT fk_reservat_as_9_voyage FOREIGN KEY (voy_id) REFERENCES public.voyage(voy_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.reservation ADD CONSTRAINT fk_reservat_aso_16_frais FOREIGN KEY (frais_id) REFERENCES public.frais(frais_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.reservation ADD CONSTRAINT fk_reservat_aso_17_mode_pay FOREIGN KEY (modep_id) REFERENCES public.mode_payement(modep_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.voyage ADD CONSTRAINT fk_voyage_apparteni_itinerai FOREIGN KEY (itin_id) REFERENCES public.itineraire(itin_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.voyage ADD CONSTRAINT fk_voyage_as_12_listage FOREIGN KEY (listage_id) REFERENCES public.listage(listage_id) ON UPDATE RESTRICT ON DELETE RESTRICT",
                "ALTER TABLE ONLY public.voyage ADD CONSTRAINT fk_voyage_as_13_type_veh FOREIGN KEY (typv_id) REFERENCES public.type_vehicule(typv_id) ON UPDATE RESTRICT ON DELETE RESTRICT"],
};

module.exports = tables;